### ISSUE TITLE
AP SSH issue?

### ISSUE THREAD

**Issue by MLWALK3R** [cardinal-dev/cardinal-docker#2]
Followed the intrusions, ran the docker added an AP ensuring all info was correct. trying to pull the info for the AP I get

Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application

cardinal_1  | Exception (client): Incompatible version (1.5 instead of 2.0)
cardinal_1  | Traceback (most recent call last):
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/transport.py", line 2093, in run
cardinal_1  |     self._check_banner()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/transport.py", line 2299, in _check_banner
cardinal_1  |     raise IncompatiblePeer(msg.format(version))
cardinal_1  | paramiko.ssh_exception.IncompatiblePeer: Incompatible version (1.5 instead of 2.0)
cardinal_1  | 
cardinal_1  | [2022-01-14 16:26:10,110] ERROR in app: Exception on /get-ap-info [POST]
cardinal_1  | Traceback (most recent call last):
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
cardinal_1  |     response = self.full_dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
cardinal_1  |     rv = self.handle_user_exception(e)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
cardinal_1  |     rv = self.dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
cardinal_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 150, in fetchApInfo
cardinal_1  |     status = gatherApInfo(apId)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/system/cardinal_fetch.py", line 55, in gatherApInfo
cardinal_1  |     apInfo = scout_info.scoutFetcher(ip=apIp, username=apSshUsername, password=apSshPassword)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/scout/scout_info.py", line 176, in scoutFetcher
cardinal_1  |     scoutSsh = scout_auth.sshInfo(ip=ip, username=username, password=password)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/scout/scout_auth.py", line 36, in sshInfo
cardinal_1  |     scoutSsh.connect(ip, port=22, username=username, password=password, look_for_keys=False, allow_agent=False)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/client.py", line 406, in connect
cardinal_1  |     t.start_client(timeout=timeout)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/transport.py", line 698, in start_client
cardinal_1  |     raise e
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/transport.py", line 2093, in run
cardinal_1  |     self._check_banner()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/paramiko/transport.py", line 2299, in _check_banner
cardinal_1  |     raise IncompatiblePeer(msg.format(version))
cardinal_1  | paramiko.ssh_exception.IncompatiblePeer: Incompatible version (1.5 instead of 2.0)

Fix that error by enabling SSH ver 2

cardinal_1  | [2022-01-14 16:51:45,475] ERROR in app: Exception on /get-ap-info [POST]
cardinal_1  | Traceback (most recent call last):
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
cardinal_1  |     response = self.full_dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
cardinal_1  |     rv = self.handle_user_exception(e)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
cardinal_1  |     rv = self.dispatch_request()
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
cardinal_1  |     return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/views/cardinal_ap_ops.py", line 150, in fetchApInfo
cardinal_1  |     status = gatherApInfo(apId)
cardinal_1  |   File "/opt/Cardinal/webapp/./cardinal/system/cardinal_fetch.py", line 55, in gatherApInfo
cardinal_1  |     apInfo = scout_info.scoutFetcher(ip=apIp, username=apSshUsername, password=apSshPassword)
cardinal_1  |   File "/opt/venv/cardinal/lib/python3.8/site-packages/scout/scout_info.py", line 198, in scoutFetcher
cardinal_1  |     apBandwidth = sshData[3].split(",")[1]
cardinal_1  | IndexError: list index out of range
cardinal_1  | [pid: 19|app: 0|req: 42/340] 172.16.250.165 () {54 vars in 1239 bytes} [Fri Jan 14 16:51:37 2022] POST /get-ap-info => generated 290 bytes in 7938 msecs (HTTP/1.1 500) 3 headers in 113 bytes (2 switches on core 0)
 
Now getting this

**Comment by falcon78921** [comment]
Hey @MLWALK3R :wave:

Just curious, which Cisco AP model are you trying to fetch info from?

**Comment by MLWALK3R** [comment]
AIR-AP2702I-UXK9

**Comment by falcon78921** [comment]
Thanks @MLWALK3R. At the moment, Cardinal is tested against a Cisco Aironet 1142N and 3602i. Not sure if there's a subtle difference with the 2602i. Possible there's a bug in `scoutFetcher()`.

When you have a chance, please invoke `scoutFetcher()` manually and then paste the full output here.

~~~
$ docker exec -u 0 -it cardinaldocker_cardinal_1 /bin/bash
root@cardinal:/opt# source /opt/venv/cardinal/bin/activate
(cardinal) root@cardinal:/opt# export PYTHONPATH=$VIRTUAL_ENV/lib/python3.8/site-packages/scout
(cardinal) root@cardinal:/opt# python
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from scout import scout_info
>>> info = scout_info.scoutFetcher("<AP_IP>", "<AP_USERNAME>", "<AP_PASSWORD>")
>>> print(info)
~~~

**Comment by falcon78921** [comment]
Proposed fix here: https://github.com/cardinal-dev/scout/issues/12
